#! /bin/sh


#  _
# | |__  ___ _ ____      ___ __ ___  _ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
# | |_) \__ \ |_) \ V  V /| | | | | | | | (__
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#           |_|

#  _________________________________________________________________ #

#  _____            _                                      _
# | ____|_ ____   _(_)_ __ ___  _ __  _ __ ___   ___ _ __ | |_
# |  _| | '_ \ \ / / | '__/ _ \| '_ \| '_ ` _ \ / _ \ '_ \| __|
# | |___| | | \ V /| | | | (_) | | | | | | | | |  __/ | | | |_
# |_____|_| |_|\_/ |_|_|  \___/|_| |_|_| |_| |_|\___|_| |_|\__|

zsh:1: command not found: figlet
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

gap=0
PANEL_HEIGHT=10

#   ____             __ _
#  / ___|___  _ __  / _(_) __ _
# | |   / _ \| '_ \| |_| |/ _` |
# | |__| (_) | | | |  _| | (_| |
#  \____\___/|_| |_|_| |_|\__, |
#                         |___/

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT + $gap))
bspc config left_padding $gap
bspc config right_padding $gap
bspc config bottom_padding $gap

bspc config border_width 1
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier
bspc config focus_follows_pointer   true
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#  ____        _
# |  _ \ _   _| | ___  ___
# | |_) | | | | |/ _ \/ __|
# |  _ <| |_| | |  __/\__ \
# |_| \_\\__,_|_|\___||___/
#

bspc rule -a Zathura state=tiled

#     _         _            _             _
#    / \  _   _| |_ ___  ___| |_ __ _ _ __| |_
#   / _ \| | | | __/ _ \/ __| __/ _` | '__| __|
#  / ___ \ |_| | || (_) \__ \ || (_| | |  | |_
# /_/   \_\__,_|\__\___/|___/\__\__,_|_|   \__|
#

sh $BSPWM_CONFIG/autostart &
